package com.xxzx.cxhk.entity;

import java.util.Date;

public class CreditInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.info_type
     *
     * @mbggenerated
     */
    private Short infoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.identity_card
     *
     * @mbggenerated
     */
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.org_code
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.credit_code
     *
     * @mbggenerated
     */
    private String creditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.check_date
     *
     * @mbggenerated
     */
    private Date checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.check_id
     *
     * @mbggenerated
     */
    private Integer checkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.modify_id
     *
     * @mbggenerated
     */
    private Integer modifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.bus_regist_no
     *
     * @mbggenerated
     */
    private Integer busRegistNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.custom_info
     *
     * @mbggenerated
     */
    private String customInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.tax_num
     *
     * @mbggenerated
     */
    private String taxNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_info.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.id
     *
     * @return the value of t_credit_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.id
     *
     * @param id the value for t_credit_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.create_date
     *
     * @return the value of t_credit_info.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.create_date
     *
     * @param createDate the value for t_credit_info.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.modify_date
     *
     * @return the value of t_credit_info.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.modify_date
     *
     * @param modifyDate the value for t_credit_info.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.info_type
     *
     * @return the value of t_credit_info.info_type
     *
     * @mbggenerated
     */
    public Short getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.info_type
     *
     * @param infoType the value for t_credit_info.info_type
     *
     * @mbggenerated
     */
    public void setInfoType(Short infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.name
     *
     * @return the value of t_credit_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.name
     *
     * @param name the value for t_credit_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.identity_card
     *
     * @return the value of t_credit_info.identity_card
     *
     * @mbggenerated
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.identity_card
     *
     * @param identityCard the value for t_credit_info.identity_card
     *
     * @mbggenerated
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.org_code
     *
     * @return the value of t_credit_info.org_code
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.org_code
     *
     * @param orgCode the value for t_credit_info.org_code
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.credit_code
     *
     * @return the value of t_credit_info.credit_code
     *
     * @mbggenerated
     */
    public String getCreditCode() {
        return creditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.credit_code
     *
     * @param creditCode the value for t_credit_info.credit_code
     *
     * @mbggenerated
     */
    public void setCreditCode(String creditCode) {
        this.creditCode = creditCode == null ? null : creditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.check_date
     *
     * @return the value of t_credit_info.check_date
     *
     * @mbggenerated
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.check_date
     *
     * @param checkDate the value for t_credit_info.check_date
     *
     * @mbggenerated
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.check_id
     *
     * @return the value of t_credit_info.check_id
     *
     * @mbggenerated
     */
    public Integer getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.check_id
     *
     * @param checkId the value for t_credit_info.check_id
     *
     * @mbggenerated
     */
    public void setCheckId(Integer checkId) {
        this.checkId = checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.modify_id
     *
     * @return the value of t_credit_info.modify_id
     *
     * @mbggenerated
     */
    public Integer getModifyId() {
        return modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.modify_id
     *
     * @param modifyId the value for t_credit_info.modify_id
     *
     * @mbggenerated
     */
    public void setModifyId(Integer modifyId) {
        this.modifyId = modifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.bus_regist_no
     *
     * @return the value of t_credit_info.bus_regist_no
     *
     * @mbggenerated
     */
    public Integer getBusRegistNo() {
        return busRegistNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.bus_regist_no
     *
     * @param busRegistNo the value for t_credit_info.bus_regist_no
     *
     * @mbggenerated
     */
    public void setBusRegistNo(Integer busRegistNo) {
        this.busRegistNo = busRegistNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.custom_info
     *
     * @return the value of t_credit_info.custom_info
     *
     * @mbggenerated
     */
    public String getCustomInfo() {
        return customInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.custom_info
     *
     * @param customInfo the value for t_credit_info.custom_info
     *
     * @mbggenerated
     */
    public void setCustomInfo(String customInfo) {
        this.customInfo = customInfo == null ? null : customInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.tax_num
     *
     * @return the value of t_credit_info.tax_num
     *
     * @mbggenerated
     */
    public String getTaxNum() {
        return taxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.tax_num
     *
     * @param taxNum the value for t_credit_info.tax_num
     *
     * @mbggenerated
     */
    public void setTaxNum(String taxNum) {
        this.taxNum = taxNum == null ? null : taxNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_info.remarks
     *
     * @return the value of t_credit_info.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_info.remarks
     *
     * @param remarks the value for t_credit_info.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}