package com.xxzx.cxhk.entity;

import java.util.Date;

public class TemplateAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.affair_category_id
     *
     * @mbggenerated
     */
    private Integer affairCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.government_id
     *
     * @mbggenerated
     */
    private Integer governmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.is_used
     *
     * @mbggenerated
     */
    private Boolean isUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.version
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.attribute_name
     *
     * @mbggenerated
     */
    private String attributeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.is_required
     *
     * @mbggenerated
     */
    private Boolean isRequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.attribute_order
     *
     * @mbggenerated
     */
    private Integer attributeOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute.attribute_type
     *
     * @mbggenerated
     */
    private Integer attributeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.id
     *
     * @return the value of t_template_attribute.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.id
     *
     * @param id the value for t_template_attribute.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.create_date
     *
     * @return the value of t_template_attribute.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.create_date
     *
     * @param createDate the value for t_template_attribute.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.modify_date
     *
     * @return the value of t_template_attribute.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.modify_date
     *
     * @param modifyDate the value for t_template_attribute.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.affair_category_id
     *
     * @return the value of t_template_attribute.affair_category_id
     *
     * @mbggenerated
     */
    public Integer getAffairCategoryId() {
        return affairCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.affair_category_id
     *
     * @param affairCategoryId the value for t_template_attribute.affair_category_id
     *
     * @mbggenerated
     */
    public void setAffairCategoryId(Integer affairCategoryId) {
        this.affairCategoryId = affairCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.government_id
     *
     * @return the value of t_template_attribute.government_id
     *
     * @mbggenerated
     */
    public Integer getGovernmentId() {
        return governmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.government_id
     *
     * @param governmentId the value for t_template_attribute.government_id
     *
     * @mbggenerated
     */
    public void setGovernmentId(Integer governmentId) {
        this.governmentId = governmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.is_used
     *
     * @return the value of t_template_attribute.is_used
     *
     * @mbggenerated
     */
    public Boolean getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.is_used
     *
     * @param isUsed the value for t_template_attribute.is_used
     *
     * @mbggenerated
     */
    public void setIsUsed(Boolean isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.version
     *
     * @return the value of t_template_attribute.version
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.version
     *
     * @param version the value for t_template_attribute.version
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.attribute_name
     *
     * @return the value of t_template_attribute.attribute_name
     *
     * @mbggenerated
     */
    public String getAttributeName() {
        return attributeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.attribute_name
     *
     * @param attributeName the value for t_template_attribute.attribute_name
     *
     * @mbggenerated
     */
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName == null ? null : attributeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.is_required
     *
     * @return the value of t_template_attribute.is_required
     *
     * @mbggenerated
     */
    public Boolean getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.is_required
     *
     * @param isRequired the value for t_template_attribute.is_required
     *
     * @mbggenerated
     */
    public void setIsRequired(Boolean isRequired) {
        this.isRequired = isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.attribute_order
     *
     * @return the value of t_template_attribute.attribute_order
     *
     * @mbggenerated
     */
    public Integer getAttributeOrder() {
        return attributeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.attribute_order
     *
     * @param attributeOrder the value for t_template_attribute.attribute_order
     *
     * @mbggenerated
     */
    public void setAttributeOrder(Integer attributeOrder) {
        this.attributeOrder = attributeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute.attribute_type
     *
     * @return the value of t_template_attribute.attribute_type
     *
     * @mbggenerated
     */
    public Integer getAttributeType() {
        return attributeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute.attribute_type
     *
     * @param attributeType the value for t_template_attribute.attribute_type
     *
     * @mbggenerated
     */
    public void setAttributeType(Integer attributeType) {
        this.attributeType = attributeType;
    }
}