package com.xxzx.cxhk.entity;

public class TemplateAttributeOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute_option.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute_option.options
     *
     * @mbggenerated
     */
    private String options;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_template_attribute_option.template_attribute_id
     *
     * @mbggenerated
     */
    private Integer templateAttributeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute_option.id
     *
     * @return the value of t_template_attribute_option.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute_option.id
     *
     * @param id the value for t_template_attribute_option.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute_option.options
     *
     * @return the value of t_template_attribute_option.options
     *
     * @mbggenerated
     */
    public String getOptions() {
        return options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute_option.options
     *
     * @param options the value for t_template_attribute_option.options
     *
     * @mbggenerated
     */
    public void setOptions(String options) {
        this.options = options == null ? null : options.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_template_attribute_option.template_attribute_id
     *
     * @return the value of t_template_attribute_option.template_attribute_id
     *
     * @mbggenerated
     */
    public Integer getTemplateAttributeId() {
        return templateAttributeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_template_attribute_option.template_attribute_id
     *
     * @param templateAttributeId the value for t_template_attribute_option.template_attribute_id
     *
     * @mbggenerated
     */
    public void setTemplateAttributeId(Integer templateAttributeId) {
        this.templateAttributeId = templateAttributeId;
    }
}