package com.xxzx.cxhk.dao.mbg;

import com.xxzx.cxhk.entity.CreditInfo;
import com.xxzx.cxhk.entity.CreditInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreditInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    int countByExample(CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    int deleteByExample(CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    int insert(CreditInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    int insertSelective(CreditInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    List<CreditInfo> selectByExample(CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    CreditInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CreditInfo record, @Param("example") CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CreditInfo record, @Param("example") CreditInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CreditInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_credit_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CreditInfo record);
}