package com.xxzx.cxhk.dao.mbg;

import com.xxzx.cxhk.entity.TemplateAttribute;
import com.xxzx.cxhk.entity.TemplateAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TemplateAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    int countByExample(TemplateAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    int deleteByExample(TemplateAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    int insert(TemplateAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    int insertSelective(TemplateAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    List<TemplateAttribute> selectByExample(TemplateAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    TemplateAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TemplateAttribute record, @Param("example") TemplateAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TemplateAttribute record, @Param("example") TemplateAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TemplateAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TemplateAttribute record);
}